### ISSUE TITLE
UI messed up in last version

### ISSUE THREAD

**Issue by sle118** [amg0/ALTUI#15]
There was a UI update at some point that messed up the layout, making it hardly usable. Below is an example in which we can see that visual elements are overlapping each other. 

https://photos.app.goo.gl/6cykOwBgZckJp0LM2

Thank you for having a look!

**Comment by amg0** [comment]
As indicated inte forum altui 2.x requires different css theme which are
based on bootstrap 4.x

You need first to reset any theme and work on standard mode then work on
your themes

Best regards

**Comment by amg0** [comment]
let me know if we can close this issue.

**Comment by amg0** [comment]
assuming issue is closed now
