### ISSUE TITLE
HTTP 404 Error on [Open] Home Page

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [amg0/ALTUI#25]
@amg0 Just installed Alternate UI from Vera App Store v2.27 onto a VeraEdge
When I click [Open] i.e `http://ip_addr/data_request?id=lr_ALTUI_Handler&command=home` I obtain a 404 error

However, it works when I add the port 3480 to the ip_addr i.e `http://ip_addr:3480/data_request?id=lr_ALTUI_Handler&command=home`

**Comment by amg0** [comment]
On vera the right url is using /port_3480 notation. Other url will lead to errors 

On openluup it is the :3480 notation that must be used

**Comment by arnoldtonderaimarunda** [comment]
Thanks, understand. 

Just thought the correct URL should be something that works 'out-of-the-box' having installed it from the Vera app store.

**Comment by amg0** [comment]
Sure, It does if you use the open button in the settings tab, otherwise of course there is the readme file here http://forum.micasaverde.com/index.php/board,78.0.html
I agree not intuitive but that’s how handlers works in Vera.

**Comment by arnoldtonderaimarunda** [comment]
Hi, understand. 

I actually reported it because on my VeraEdge deployment the ALTUI Home Page [Open] button within the AltUI device settings is going to http://192.168.254.13/data_request?id=lr_ALTUI_Handler&command=home 
leading to a 404 error instead of 
http://192.168.254.13/port_3480/data_request?id=lr_ALTUI_Handler&command=home
