### ISSUE TITLE
feature request: Vera and the infamous back button

### ISSUE THREAD

**Issue by sle118** [amg0/ALTUI#5]
I have long been frustrated by the lack of proper browser history support in Vera UI and I would like to propose a change which might just allow using back/forward buttons on the browser when navigating the interface. 

Given that all the navigation is done as part of back end calls, why not manipulate the browser history?
https://developer.mozilla.org/en-US/docs/Web/API/History_API

**Comment by amg0** [comment]
it cannot work, ALTUI is 100% one single page application and individual application area/pages are not accessible by a url so even pushing a url into the history wont solve it. we need a history mecanism for 100% ajax based apps

**Comment by amg0** [comment]
fixed in 1981 release and +
